### ISSUE TITLE
关于模型下载问题

### ISSUE THREAD

**Issue by love112358** [tumuyan/realsr-models#1]
当我在下载这些模型的时候，遇到如下问题，下载里面的bin文件显示只有几k大小 几乎所有的模型都是如此，
![image](https://github.com/tumuyan/realsr-models/assets/33959491/bfafa2c6-893b-4dee-ac20-d536e2661574)
![image](https://github.com/tumuyan/realsr-models/assets/33959491/ff3c22b8-bf0d-442b-b61d-85653bc828fd)

打开bin文件显示的是
version https://git-lfs.github.com/spec/v1
oid sha256:8301319c42ddba71922c4424098fe0a2088a5f1f94f6ef4bcf1385e17b2bc053
size 20085364
这么才能直接下载 完整的bin文件呢
你能弄成压缩文件上传一下吗

**Comment by tumuyan** [comment]
原因可能是文件太大，github限流了
事情挺麻烦的，之前我传了huggingface蛮多东西，1月huggingface把我帐号删掉了，申诉没有回复。
我把仓库上传到github，收到了github给我发送的流量超出的mail
可能还是得传网盘...

**Comment by love112358** [comment]
辛苦了 谢谢 麻烦你好多了  @tumuyan

**Comment by tumuyan** [comment]
重新上传了huggingface
https://huggingface.co/tumuyan2/realsr-models
