### ISSUE TITLE
404 on huggingface

### ISSUE THREAD

**Issue by fukiame** [tumuyan/realsr-models#2]
![Screenshot_20240308-131217_Mulch_1](https://github.com/tumuyan/realsr-models/assets/122709956/1d570d45-99e3-49d5-9216-698fdaef4827)
https://huggingface.co/tumuyan/realsr/tree/main

**Comment by tumuyan** [comment]
My account was delete but I don't know why.
Since github download lfs files has some limit, I upload to hf again.
https://huggingface.co/tumuyan2/realsr-models
